# encoding: UTF-8
---
driver:
  name: vagrant
  customize:
    memory: 512
    numvcpus: 2

provisioner:
  name: chef_zero
  require_chef_omnibus: true

platforms:
  - name: centos-6.5

suites:
  - name: default
    run_list:
      - recipe[test_fixtures::devreporter]
      - recipe[websphere::iim]
    attributes:
      websphere:
        prune_zipfiles: false
