# -*- coding: utf-8 -*-

AllCops:
  Include:
    - Gemfile
    - attributes/**/*
    - recipes/**/*
    - libraries/**/*
    - providers/**/*
    - resources/**/*
  Exclude:
    - test/**/*
    - vendor/**/*
    - debug_shell.rb

SingleSpaceBeforeFirstArg:
  Exclude:
    - '**/metadata.rb'
    - recipes/**/*

LineLength:
  Enabled: false
